name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '16.x'
      
      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm test